# Pengenalan & Komputasi Array NumPy

Pernahkah Anda bertanya:
> *"Python kan sudah punya tipe data List untuk menyimpan banyak data sekaligus. Kenapa kita masih butuh NumPy?"*

Jawabannya ada pada **kecepatan komputasi** dan **efisiensi memori**.

**List bawaan Python** dirancang sangat fleksibel—ia bisa menyimpan angka, teks, dan boolean dalam satu wadah. Namun karena terlalu fleksibel, komputer harus menyimpan setiap elemen di lokasi memori yang terpisah-pisah (*pointer heap*). Ketika data Anda berjumlah jutaan baris, melakukan perhitungan matematika dengan List akan terasa sangat lambat.

Di sinilah **NumPy** (*Numerical Python*) hadir. NumPy menyimpan data bertipe seragam (*homogeneous*) secara berurutan di dalam satu blok memori komputer yang padat (*contiguous array*). NumPy ditulis menggunakan bahasa C, sehingga kalkulasi matematikanya dijalankan langsung di tingkat perangkat keras (*hardware level*) dengan kecepatan hingga puluhan kali lebih cepat dibanding List biasa.

## 1. Memasang Pustaka NumPy

Sebelum menggunakan NumPy, pastikan pustaka ini sudah terpasang. Di Google Colab pustaka ini sudah tersedia, tetapi di laptop lokal Anda bisa memasangnya lewat perintah pip:

In [1]:
! pip install numpy


[notice] A new release of pip available: 22.2.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## 2. Bukti Nyata: Uji Kecepatan (List vs NumPy Array)

Mari kita buktikan klaim kecepatannya dengan mengalikan **1 juta angka** menggunakan List biasa dibandingkan dengan NumPy Array:

In [2]:
import numpy as np
import time

# Menyiapkan 1 juta data angka
jumlah_data = 1_000_000
list_python = list(range(jumlah_data))
array_numpy = np.arange(jumlah_data)

# Uji kecepatan Python List biasa
waktu_mulai = time.time()
hasil_list = [x * 2 for x in list_python]
durasi_list = time.time() - waktu_mulai

# Uji kecepatan NumPy Array
waktu_mulai = time.time()
hasil_numpy = array_numpy * 2
durasi_numpy = time.time() - waktu_mulai

print(f"Waktu Python List : {durasi_list:.4f} detik")
print(f"Waktu NumPy Array : {durasi_numpy:.4f} detik")
print(f"Hasil: NumPy sekitar {durasi_list / durasi_numpy:.1f}x lebih cepat!")

Waktu Python List : 0.0802 detik
Waktu NumPy Array : 0.0047 detik
Hasil: NumPy sekitar 17.0x lebih cepat!


## 3. Membuat Array 1 Dimensi (Vektor) & 2 Dimensi (Matriks)

Untuk membuat array, kita memasukkan list ke dalam fungsi `np.array()`. NumPy memiliki beberapa atribut penting untuk memeriksa struktur data kita:
* `shape`: Menampilkan ukuran dimensi (baris, kolom).
* `ndim`: Menampilkan jumlah dimensi (1D atau 2D).
* `dtype`: Menampilkan tipe data elemen (misal `int64` atau `float64`).
* `size`: Menampilkan total seluruh elemen di dalam array.

In [3]:
# 1. Array 1 Dimensi (Vektor)
vektor = np.array([10, 20, 30, 40, 50])
print("Array 1D :", vektor)
print("Bentuk   :", vektor.shape)
print("Tipe data:", vektor.dtype)

# 2. Array 2 Dimensi (Matriks tabel baris dan kolom)
matriks = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nMatriks 2D:\n", matriks)
print("Bentuk (baris, kolom):", matriks.shape)
print("Total elemen         :", matriks.size)

Array 1D : [10 20 30 40 50]
Bentuk   : (5,)
Tipe data: int64

Matriks 2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Bentuk (baris, kolom): (3, 3)
Total elemen         : 9


## 4. Fungsi Pembuat Array Instan

Sering kali kita butuh membuat array berisi angka awal tanpa harus mengetik satu per satu secara manual:
* `np.zeros((baris, kolom))`: Membuat array berisi angka 0 (biasa dipakai sebagai wadah penampung awal).
* `np.ones((baris, kolom))`: Membuat array berisi angka 1.
* `np.arange(awal, akhir, langkah)`: Membuat deret angka urut (mirip fungsi `range` bawaan Python).
* `np.linspace(awal, akhir, jumlah_titik)`: Membuat titik-titik angka berjarak sama rata.

In [4]:
# Array angka nol ukuran 2 baris x 4 kolom
nol = np.zeros((2, 4))
print("Array Nol (2x4):\n", nol)

# Deret angka genap dari 0 sampai sebelum 20 (kelipatan 2)
genap = np.arange(0, 20, 2)
print("\nDeret Genap:", genap)

# 5 titik angka yang berjarak sama dari 0 sampai 1
titik_rata = np.linspace(0, 1, 5)
print("\nLinspace (0 s.d 1):", titik_rata)

Array Nol (2x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Deret Genap: [ 0  2  4  6  8 10 12 14 16 18]

Linspace (0 s.d 1): [0.   0.25 0.5  0.75 1.  ]


## 5. Mengakses dan Memotong Data (Indexing & Slicing)

Bagaimana cara mengambil baris tertentu, kolom tertentu, atau angka spesifik di dalam matriks? Format standarnya adalah:
$$\text{matriks}[\text{indeks\_baris},\ \text{indeks\_kolom}]$$

Gunakan tanda titik dua `:` untuk mengambil seluruh data pada baris atau kolom tersebut.

In [5]:
tabel_nilai = np.array([
    [80, 85, 90],
    [75, 70, 88],
    [92, 95, 89]
])

# Mengambil satu angka spesifik (baris ke-1, kolom ke-2 -> indeks [0, 1])
print("Nilai baris 1, kolom 2 :", tabel_nilai[0, 1])

# Mengambil seluruh baris kedua (indeks baris 1, semua kolom)
print("Baris kedua penuh      :", tabel_nilai[1, :])

# Mengambil seluruh kolom ketiga (semua baris, indeks kolom 2)
print("Kolom ketiga penuh     :", tabel_nilai[:, 2])

Nilai baris 1, kolom 2 : 85
Baris kedua penuh      : [75 70 88]
Kolom ketiga penuh     : [90 88 89]


## 6. Operasi Matematika Vektorisasi (Vectorization)

Kelebihan utama NumPy adalah operasi matematika langsung diterapkan ke setiap elemen secara serentak tanpa perlu membuat perulangan `for` (*vectorization*):

In [6]:
harga = np.array([10000, 25000, 50000, 75000])
diskon = 0.10  # Diskon 10%

# Menghitung harga setelah diskon langsung ke seluruh array
harga_setelah_diskon = harga - (harga * diskon)
print("Harga awal            :", harga)
print("Harga setelah diskon  :", harga_setelah_diskon)

# Penjumlahan dua array yang berukuran sama
ongkir = np.array([2000, 3000, 5000, 4000])
total_bayar = harga_setelah_diskon + ongkir
print("Total bayar (+ ongkir):", total_bayar)

Harga awal            : [10000 25000 50000 75000]
Harga setelah diskon  : [ 9000. 22500. 45000. 67500.]
Total bayar (+ ongkir): [11000. 25500. 50000. 71500.]


## 7. Menyaring Data Berdasarkan Kondisi (Boolean Indexing)

Dalam analisis data, kita sangat sering menyaring angka yang memenuhi kriteria tertentu (misalnya nilai di atas batas kelulusan atau penjualan di atas target).

Di NumPy, Anda cukup memasukkan kondisi logika ke dalam kurung siku `array[kondisi]`. Ini jauh lebih cepat dan bersih daripada membuat percabangan `if` di dalam loop.

In [7]:
skor_ujian = np.array([65, 82, 58, 90, 74, 88, 95, 60, 78])
batas_lulus = 75

# Melihat hasil kondisi boolean (True/False)
lulus_mask = skor_ujian >= batas_lulus
print("Status kelulusan (Boolean):", lulus_mask)

# Mengambil hanya angka yang bernilai True
skor_lulus = skor_ujian[skor_ujian >= batas_lulus]
print("Daftar skor yang lulus (>= 75):", skor_lulus)
print("Jumlah peserta yang lulus     :", len(skor_lulus))

Status kelulusan (Boolean): [False  True False  True False  True  True False  True]
Daftar skor yang lulus (>= 75): [82 90 88 95 78]
Jumlah peserta yang lulus     : 5


## 8. Mengubah Dimensi Array (`reshape`)

Dalam analisis data dan machine learning, kita sering kali perlu mengubah susunan data dari 1 dimensi (deret angka) menjadi tabel 2 dimensi (baris x kolom), misalnya mengubah 12 data bulanan menjadi matriks 3 kuartal x 4 bulan.

Gunakan method `.reshape(baris, kolom)`. Syaratnya: total jumlah elemen awal dan akhir harus sama persis.

In [8]:
# Deret 12 angka urut
data_12 = np.arange(1, 13)
print("Array 1D awal:", data_12)

# Ubah menjadi matriks 3 baris x 4 kolom
matriks_3x4 = data_12.reshape(3, 4)
print("\nMatriks 3 baris x 4 kolom:\n", matriks_3x4)

# Ubah menjadi matriks 4 baris x 3 kolom
matriks_4x3 = data_12.reshape(4, 3)
print("\nMatriks 4 baris x 3 kolom:\n", matriks_4x3)

Array 1D awal: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Matriks 3 baris x 4 kolom:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matriks 4 baris x 3 kolom:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 9. Menghitung Statistik Cepat dengan NumPy

NumPy menyediakan fungsi statistik bawaan berkinerja tinggi untuk meringkas data angka numerik:

In [9]:
data_penjualan = np.array([45, 82, 67, 90, 54, 78, 88, 95, 72, 84])

print("Total Keseluruhan (Sum) :", np.sum(data_penjualan))
print("Rata-rata (Mean)        :", np.mean(data_penjualan))
print("Nilai Tengah (Median)   :", np.median(data_penjualan))
print("Standar Deviasi (Std)   :", round(np.std(data_penjualan), 2))
print("Penjualan Terendah (Min):", np.min(data_penjualan))
print("Penjualan Tertinggi(Max):", np.max(data_penjualan))

Total Keseluruhan (Sum) : 755
Rata-rata (Mean)        : 75.5
Nilai Tengah (Median)   : 80.0
Standar Deviasi (Std)   : 15.31
Penjualan Terendah (Min): 45
Penjualan Tertinggi(Max): 95


## 10. Studi Kasus Nyata: Analisis Penjualan Mingguan 3 Cabang Toko

Mari kita terapkan seluruh konsep yang telah dipelajari ke dalam studi kasus nyata.

Sebuah jaringan toko ritel memiliki **3 cabang** (Cabang Jakarta, Surabaya, dan Bandung). Data penjualan produk selama 7 hari (Senin s.d. Minggu) dicatat ke dalam satu matriks 2 dimensi ukuran **3 baris x 7 kolom**.

Tugas kita:
1. Menghitung total penjualan masing-masing cabang dalam seminggu (`axis=1`).
2. Menghitung rata-rata penjualan harian seluruh cabang gabungan (`axis=0`).
3. Menentukan cabang mana yang memiliki penjualan tertinggi.

In [10]:
# Data penjualan 3 cabang selama 7 hari (Senin s.d. Minggu)
penjualan_mingguan = np.array([
    [15, 18, 20, 22, 25, 30, 28],  # Cabang Jakarta
    [10, 12, 11, 14, 16, 20, 18],  # Cabang Surabaya
    [20, 24, 26, 25, 32, 38, 35]   # Cabang Bandung
])

nama_cabang = ['Jakarta', 'Surabaya', 'Bandung']

# 1. Total penjualan per cabang (penjumlahan mendatar / per baris: axis=1)
total_per_cabang = np.sum(penjualan_mingguan, axis=1)

# 2. Rata-rata penjualan per cabang
rata_per_cabang = np.mean(penjualan_mingguan, axis=1)

print("=== Laporan Performa Mingguan Toko Ritel ===")
for nama, total, rata in zip(nama_cabang, total_per_cabang, rata_per_cabang):
    print(f"Cabang {nama:<9}: Total = {total} unit | Rata-rata = {rata:.1f} unit/hari")

# 3. Menentukan cabang dengan penjualan tertinggi
indeks_terbaik = np.argmax(total_per_cabang)
print(f"\nCabang dengan performa terbaik: Cabang {nama_cabang[indeks_terbaik]} ({total_per_cabang[indeks_terbaik]} unit)")

# 4. Rata-rata penjualan harian seluruh cabang gabungan (penjumlahan tegak / per kolom: axis=0)
hari = ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min']
rata_harian = np.mean(penjualan_mingguan, axis=0)
print("\nRata-rata penjualan gabungan per hari:")
for h, r in zip(hari, rata_harian):
    print(f"{h}: {r:.1f} unit", end=" | ")
print()

=== Laporan Performa Mingguan Toko Ritel ===
Cabang Jakarta  : Total = 158 unit | Rata-rata = 22.6 unit/hari
Cabang Surabaya : Total = 101 unit | Rata-rata = 14.4 unit/hari
Cabang Bandung  : Total = 200 unit | Rata-rata = 28.6 unit/hari

Cabang dengan performa terbaik: Cabang Bandung (200 unit)

Rata-rata penjualan gabungan per hari:
Sen: 15.0 unit | Sel: 18.0 unit | Rab: 19.0 unit | Kam: 20.3 unit | Jum: 24.3 unit | Sab: 29.3 unit | Min: 27.0 unit | 
