# Pengenalan & Komputasi Array NumPy

**NumPy** (*Numerical Python*) adalah pustaka dasar untuk komputasi ilmiah dalam Python. NumPy menyediakan struktur data **ndarray** (*N-dimensional array*) yang jauh lebih cepat dan hemat memori dibandingkan list bawaan Python.

## 1. Instalasi Pustaka NumPy
Sebelum menggunakan NumPy di lingkungan lokal atau Google Colab, pastikan pustaka sudah terpasang menggunakan perintah `pip install`:

In [1]:
! pip install numpy

## 2. Inisiasi dan Membuat Array NumPy

In [2]:
import numpy as np

# Membuat Array 1 Dimensi (Vektor)
arr_1d = np.array([10, 20, 30, 40, 50])
print("Array 1D:", arr_1d)
print("Bentuk (shape):", arr_1d.shape)
print("Tipe data (dtype):", arr_1d.dtype)

# Membuat Array 2 Dimensi (Matriks)
matrix_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nMatriks 2D:\n", matrix_2d)
print("Dimensi (ndim):", matrix_2d.ndim)
print("Ukuran (size):", matrix_2d.size)

Array 1D: [10 20 30 40 50]
Bentuk (shape): (5,)
Tipe data (dtype): int64

Matriks 2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensi (ndim): 2
Ukuran (size): 9


## 3. Fungsi Pembuat Array Otomatis
NumPy menyediakan fungsi instan untuk membuat array bernilai nol, satu, deret, atau nilai acak.

In [3]:
# Array berisi nol (zeros)
zeros = np.zeros((2, 4))

# Array berisi deret angka urut (arange)
deret = np.arange(0, 20, 2)  # start=0, stop=20, step=2

# Array linear space (linspace)
lin = np.linspace(0, 1, 5)  # 5 titik berjarak sama dari 0 s.d. 1

print("Zeros (2x4):\n", zeros)
print("Arange (kelipatan 2):", deret)
print("Linspace (0 s.d. 1):", lin)

Zeros (2x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Arange (kelipatan 2): [ 0  2  4  6  8 10 12 14 16 18]
Linspace (0 s.d. 1): [0.   0.25 0.5  0.75 1.  ]


## 4. Operasi Matematika Vektorisasi (Vectorization)
Salah satu keunggulan terbesar NumPy adalah operasi aritmatika dieksekusi secara instan per elemen (*element-wise*) tanpa perlu menuliskan perulangan `for`.

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Penjumlahan (a + b) =", a + b)
print("Perkalian (a * 3)   =", a * 3)
print("Kuadrat (a ** 2)    =", a ** 2)
print("Sinus np.sin(a)     =", np.round(np.sin(a), 4))

Penjumlahan (a + b) = [11 22 33 44]
Perkalian (a * 3)   = [ 3  6  9 12]
Kuadrat (a ** 2)    = [ 1  4  9 16]
Sinus np.sin(a)     = [ 0.8415  0.9093  0.1411 -0.7568]


## 5. Fungsi Agregasi Statistik NumPy

In [5]:
data_sampel = np.array([45, 82, 67, 90, 54, 78, 88, 95, 72, 84])

print("Rata-rata (Mean)      :", np.mean(data_sampel))
print("Median (Nilai Tengah) :", np.median(data_sampel))
print("Standar Deviasi (Std) :", np.std(data_sampel))
print("Varians (Variance)    :", np.var(data_sampel))
print("Nilai Minimum         :", np.min(data_sampel))
print("Nilai Maksimum        :", np.max(data_sampel))

Rata-rata (Mean)      : 75.5
Median (Nilai Tengah) : 80.0
Standar Deviasi (Std) : 15.311760186209813
Varians (Variance)    : 234.45
Nilai Minimum         : 45
Nilai Maksimum        : 95
